### ISSUE TITLE
failures / false positives

### ISSUE THREAD

**Issue by flatcap** [neomutt/iwyu#3]
There are 686 source files and headers (excluding the test code).
**682 of the 686 have the correct includes.**

I use this `find` to pass them to `include-what-you-use`:

```sh
find . \( -name .git -o -name queue.h -o -path './test/*' -o -path './autosetup/*' -o -path './docs/*' \) -prune -o -type f -name '*.[ch]' -print | sed 's/^\.\///' | sort | xargs iwyu.sh
```

### Unwanted Output

I get warnings for:

- `/usr/include/gnutls/gnutls.h`
- `/usr/include/gsasl.h`

### Mixed Messages

Most inclusions work correctly for:

- `config/lib.h`
- `core/lib.h`

But I get one error for each:

```
config/lib.h should add these lines:
#include "config/address.h"
#include "config/bool.h"
#include "config/charset.h"
#include "config/dump.h"
#include "config/enum.h"
#include "config/helpers.h"
#include "config/inheritance.h"
#include "config/mbtable.h"
#include "config/quad.h"
#include "config/regex2.h"
#include "config/set.h"
#include "config/sort2.h"
#include "config/subset.h"
#include "config/types.h"
```

and

```
core/lib.h should add these lines:
#include "core/account.h"
#include "core/command.h"
#include "core/config_cache.h"
#include "core/dispatcher.h"
#include "core/mailbox.h"
#include "core/message.h"
#include "core/mxapi.h"
#include "core/neomutt.h"
#include "core/tmp.h"
```

### Complicated source

Then there's the complicated stuff:

- `conn/openssl.c`
- `gui/mutt_curses.h`
- `gui/resize.c`
- `gui/terminal.c`

They give me:

```
conn/openssl.c should add these lines:
#include <openssl/pemerr.h>
#include <openssl/ssl3.h>
#include <openssl/types.h>

conn/openssl.c should remove these lines:
- #include <openssl/ossl_typ.h>
- #include <openssl/ssl.h>

gui/mutt_curses.h should add these lines:
#include <curses.h>

gui/mutt_curses.h should remove these lines:
- #include <ncursesw/ncurses.h>

gui/mutt_curses.h should add these lines:
#include <curses.h>
#include "mutt_curses.h"

gui/mutt_curses.h should remove these lines:
- #include <ncursesw/ncurses.h>

gui/resize.c should remove these lines:
- #include <termios.h>

gui/terminal.c should remove these lines:
- #include <ncursesw/term.h>
```

The headers being included here tend to vary across platforms, so these errors may not be fixable.

---

**Tooling**:
- clang version 16.0.6 (Fedora 16.0.6-2.fc38)
- include-what-you-use 0.20 based on clang version 16.0.6 (Fedora 16.0.6-2.fc38)

**Comment by roccoblues** [comment]
> ```shell
> find . \( -name .git -o -name queue.h -o -path './test/*' -o -path './autosetup/*' -o -path './docs/*' \) -prune -o -type f -name '*.[ch]' -print | sed 's/^\.\///' | sort | xargs iwyu.sh
> ```

This definitely gives me way more warnings. I you want I can paste the whole output somewhere. I don't think we'll ever make it really portable.

> But I get one error for each:
> 
> ```
> config/lib.h should add these lines:
> core/lib.h should add these lines:
> ```

Interestingly *this two* work for me:

```
 ../iwyu/bin/iwyu.sh core/lib.h config/lib.h

(core/lib.h has correct #includes/fwd-decls)

(config/lib.h has correct #includes/fwd-decls)

```

Wait, if I run the whole tree I see a similar error:
```
core/lib.h should add these lines:
#include "core/account.h"
#include "core/command.h"
#include "core/config_cache.h"
#include "core/dispatcher.h"
#include "core/mailbox.h"
#include "core/message.h"
#include "core/mxapi.h"
#include "core/neomutt.h"
#include "core/tmp.h"

core/lib.h should remove these lines:

The full include-list for core/lib.h:
#include "account.h"
#include "command.h"
#include "config_cache.h"
#include "core/account.h"
#include "core/command.h"
#include "core/config_cache.h"
#include "core/dispatcher.h"
#include "core/mailbox.h"
#include "core/message.h"
#include "core/mxapi.h"
#include "core/neomutt.h"
#include "core/tmp.h"
#include "dispatcher.h"
#include "mailbox.h"
#include "message.h"
#include "mxapi.h"
#include "neomutt.h"
#include "tmp.h"
```

**sys/**:
The majority of the errors I see seem to be related to `sys` headers:
```
send/sendmail.c should add these lines:
#include <sys/errno.h>
#include <sys/fcntl.h>
#include <sys/signal.h>
#include <sys/syslimits.h>

send/sendmail.c should remove these lines:
- #include <errno.h>
- #include <fcntl.h>
- #include <limits.h>
- #include <regex.h>

[...]

pop/pop.c should add these lines:
#include <sys/errno.h>
#include <sys/syslimits.h>

pop/pop.c should remove these lines:
- #include <errno.h>
- #include <limits.h>

[...]

mutt/state.c should add these lines:
#include <arm/limits.h>

mutt/state.c should remove these lines:
- #include <limits.h>

[...]

gui/resize.c should add these lines:
#include <sys/fcntl.h>
#include <sys/ttycom.h>

gui/resize.c should remove these lines:
- #include <fcntl.h>
- #include <termios.h>

...
```

**Tooling**:
* Homebrew clang version 16.0.6 (arm64-apple-darwin22.6.0)
* include-what-you-use 0.20 based on Homebrew clang version 16.0.6

**Comment by flatcap** [comment]
I've just had a look at the versions of clang and iwyu in GitHub's `ubuntu-latest`:

- Ubuntu clang version 14.0.0-1ubuntu1.1
- include-what-you-use 0.17 based on Ubuntu clang version 13.0.1-2ubuntu2.2

and my [Fedora 38 docker](https://github.com/neomutt/docker-build) (used for weekly builds)

- clang version 16.0.6 (Fedora 16.0.6-2.fc38)
-  include-what-you-use 0.20 based on clang version 16.0.6 (Fedora 16.0.6-2.fc38)

**Comment by flatcap** [comment]
> send/sendmail.c should add these lines:
> #include <sys/errno.h>
> 
> send/sendmail.c should remove these lines:
> - #include <errno.h>

That may be workaround-able.

There are some magic rules for [glibc](https://github.com/neomutt/iwyu/blob/main/imp/glibc.imp), [curses](https://github.com/neomutt/iwyu/blob/main/imp/curses.imp) and [regex](https://github.com/neomutt/iwyu/blob/main/imp/regex.imp).

They define how to handle certain headers / symbols.

**Comment by roccoblues** [comment]
> That may be workaround-able.
> 
> There are some magic rules for [glibc](https://github.com/neomutt/iwyu/blob/main/imp/glibc.imp), [curses](https://github.com/neomutt/iwyu/blob/main/imp/curses.imp) and [regex](https://github.com/neomutt/iwyu/blob/main/imp/regex.imp).
> 
> They define how to handle certain headers / symbols.

you mean something like this: https://github.com/neomutt/iwyu/pull/4 ?
